# Generated by Django 5.0.1 on 2024-07-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
