<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-07-19 05:51

import django.core.validators
import django.utils.timezone
from django.db import migrations, models
=======
# Generated by Django 4.2.13 on 2024-07-19 05:50

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
>>>>>>> jihun


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigorsmall', models.BooleanField()),
                ('attacker_card', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('revenger_card', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
=======
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bigorsmall", models.BooleanField()),
                (
                    "attacker_card",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "revenger_card",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
>>>>>>> jihun
            ],
        ),
    ]
