<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-07-19 05:51

import django.db.models.deletion
from django.db import migrations, models
=======
# Generated by Django 4.2.13 on 2024-07-19 05:50

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> jihun


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('game', '0001_initial'),
        ('users', '0001_initial'),
=======
        ("game", "0001_initial"),
        ("users", "0001_initial"),
>>>>>>> jihun
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='game',
            name='attacker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack_game', to='users.users'),
        ),
        migrations.AddField(
            model_name='game',
            name='revenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenge_game', to='users.users'),
=======
            model_name="game",
            name="attacker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attack_game",
                to="users.users",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="revenger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revenge_game",
                to="users.users",
            ),
>>>>>>> jihun
        ),
    ]
