# Generated by Django 4.2.13 on 2024-07-19 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="attacker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attack_game",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="revenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revenge_game",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
