# Generated by Django 4.2.13 on 2024-07-19 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="attacker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attack_game",
                to="users.users",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="revenger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revenge_game",
                to="users.users",
            ),
        ),
    ]
